# qBittorrent configuration
qbt:
  # The URL to qBittorrent's WebUI
  url: http://localhost:8080
  # The username to log in with
  username: admin
  # The password to log in with
  password: adminadmin
  # The category to add torrents to
  category: null
# The series to watch/track/download
series:
  # The RSS feed to watch, must be from nyaa.si RSS
  - rss: https://nyaa.si/?page=rss&q=Heavenly+Delusion&c=1_2&f=0&u=Tsundere-Raws
    # The regex to match the episode number and the season from the torrent title
    # for example you have: Heavenly Delusion S01E01 1080p WEB H.264 AAC -Tsundere-Raws (DSNP) (Tengoku Daimakyou / MultiSubs)
    # in the torrent title, you can use: Heavenly Delusion S(?P<season>\d+)E(?P<episode>\d+)
    # to match the season and episode number
    # The `episode` match group is required, the `season` match group is optional
    # See more about regex: https://regex101.com/
    episode_regex: Heavenly Delusion S(?P<season>\d+)E(?P<episode>\d+)
    # The series folder that Jellyfin will use, the downloaded torrent will be moved to this folder
    target_dir: /home/nao/jellyfin-library/Heavenly Delusion
    # The season number, if you don't have a season number in the torrent title
    # you can set this to 1, or whatever as a fallback
    season: 1
    # Extra matches to check for in the torrent title, case insensitive
    matches:
    - 1080p
    - DSNP
    # Ignore keyword matches, case insensitive
    ignore_matches:
    - 720p
    - DUAL
    # The time the episode will air, this is used to determine if we should download the episode
    # or not by checking if the current time is near the airtime with the provided grace period
    airtime: 2023-04-06T22:30:00+09:00
    # The grace period in minutes, used with airtime to determine if we should download the episode
    # or not by checking if the current time is near the airtime with the provided grace period.
    grace_period: 120

